GET http://localhost:8080/transaction

GET http://localhost:8080/transaction/1

POST http://localhost:8080/transaction
Content-Type: application/json 

{
    "ID": "4", 
    "From": "Zoe", 
    "To": "Kelly", 
    "Amt": 68.90
    }
